### ISSUE TITLE
csync2 2.0 do not work   with  command :  csync2 -vx -C xxx

### ISSUE THREAD

**Issue by keramist** [LINBIT/csync2#1]
csync2 2.0 do not work   with  command   csync2 -vx -C xxx
csync2 -vx -C xxx

centos 7.2  iptables close or open
when use  csync2 -vx
all works with node name  centos20 //centos30

//////////////////////
#/etc/csync2/csync2.cfg
nossl * *;
group centos
{
        host centos10;
        host centos20;
        host centos30;
        key /etc/csync2/csync2.key;
        include /home/data/wwwroot/www.antbay.com;
        exclude *~ .*;
        auto younger;
}
////////////////////

/etc/csync2/csync2_centos10.cfg 
is same above also other node

but  when use
csync2 -vx -C centos10
Connecting to host centos30 (PLAIN) ...
Connect to 192.168.1.30:30865 (centos30).
Config command failed.
ERROR: Connection to remote host `centos30' failed.
Host stays in dirty state. Try again later...

can you resolve it?

/etc/xinetd.d/csync2

# default: on
# description: csync2
service csync2
////////////////////////
{
	disable	= no
	flags		= REUSE IPv4
	socket_type	= stream
	wait		= no
	user		= root
	group		= root
	server		= /usr/sbin/csync2
	server_args	= -i -l
	#log_on_failure	+= USERID
	# only_from	= 192.168.199.3 192.168.199.4
}

////////////////////

i add IPv4 on flags if not it listening on ipv6 no ipv4

use rpm or compile all the same problem

**Comment by lge** [comment]
well, the "verbose" (or debug) log of the peer node may have shown. But likely the requested config was simply missing on that peer. You have to have similar (usually: identical) csync2 config files on all peers. Closing -- issue was 2.5 years old already.
