### ISSUE TITLE
Suppress offline hosts

### ISSUE THREAD

**Issue by DocMAX** [LINBIT/csync2#11]
Would be grat if offline host messages can be suppressed to keep the logs clean. Thx.
```
cal0.warn: Mar 22 06:05:04 csync2[18186]: ERROR: Connection to remote host `x1c' failed.
cal0.warn: Mar 22 06:05:07 csync2[18186]: ERROR: Connection to remote host `htpc' failed.
cal0.warn: Mar 22 06:05:10 csync2[18186]: ERROR: Connection to remote host `game' failed.
cal0.warn: Mar 22 06:05:10 csync2[18186]: Finished with 3 errors.
```

**Comment by lge** [comment]
On Fri, Mar 22, 2019 at 01:28:11PM +0000, DocMAX wrote:
> Would be grat if offline host messages can be suppressed to keep the logs clean. Thx.
> ```
> cal0.warn: Mar 22 06:05:04 csync2[18186]: ERROR: Connection to remote host `x1c' failed.
> cal0.warn: Mar 22 06:05:07 csync2[18186]: ERROR: Connection to remote host `htpc' failed.
> cal0.warn: Mar 22 06:05:10 csync2[18186]: ERROR: Connection to remote host `game' failed.
> cal0.warn: Mar 22 06:05:10 csync2[18186]: Finished with 3 errors.
> ```

And how is csync2 supposed to know that the host
is *supposed* to be offline?

if *you* know which peers are supposed to be reachable,
just give csync2 an explicit list of nodes to connect to.

csync2 -P peer1,peer2,peer3 ...

**Comment by DocMAX** [comment]
ok, based on this i did, better ideas are welcome:

`csync2 -x -P t420$(nc -z htpc 22 && echo ,htpc)$(nc -z game 22 && echo ,game)$(nc -z x1c 22 && echo ,x1c)$(nc -z server 22 && echo ,server)`
