### ISSUE TITLE
Fedora 31 - coredump (*** stack smashing detected ***: <unknown> terminated)

### ISSUE THREAD

**Issue by mvrk69** [LINBIT/csync2#23]
Hi,

I'm having this issue on my Fedora 31 :

# /usr/sbin/csync2 -xrv
Connecting to host XXX (SSL) ...
Updating /etc/sysconfig/garb on XXX ...
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)

Any ideas?

**Comment by ROBERT-MCDOWELL** [comment]
maybe regenerate the sql db file....

**Comment by mvrk69** [comment]
I just deleted db file on both nodes, but i have same problem:

# csync2 -xrv
Marking file as dirty: /root/bin
Marking file as dirty: /etc/sysconfig/network-scripts/route-eth0
Marking file as dirty: /etc/sysconfig/garb
Marking file as dirty: /etc/hosts
Marking file as dirty: /etc/haproxy/haproxy.cfg
Marking file as dirty: /etc/csync2/csync2.cfg
Connecting to host XXX (SSL) ...
Updating /etc/csync2/csync2.cfg on XXX ...
Received record packet of unknown type 42
While syncing file /etc/csync2/csync2.cfg:
ERROR from peer XXX: Connection closed.
File stays in dirty state. Try again later...
ERROR from peer XXX: Connection closed.
Finished with 2 errors.

# csync2 -f /etc/csync2/csync2.cfg
# csync2 -xrv
Connecting to host XXX (SSL) ...
Updating /etc/csync2/csync2.cfg on XXX ...
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)

**Comment by ROBERT-MCDOWELL** [comment]
you certainly have conflict betwen sqlite2 and sqlite3
check in /var/lib/csync2 if you see xxx.db or xxx.db3

**Comment by mvrk69** [comment]
ls -l /var/lib/csync2/
total 16
-rw-r--r-- 1 root root 16384 Feb 20 13:38 XXX.db

**Comment by ROBERT-MCDOWELL** [comment]
that's it, it should be xxx.db3
try to remove from your OS sqlite2 packages

**Comment by mvrk69** [comment]
rpm -e sqlite2-2.8.17-28.fc31.x86_64
error: Failed dependencies:
	libsqlite.so.0()(64bit) is needed by (installed) csync2-1.34-25.fc31.x86_64

**Comment by ROBERT-MCDOWELL** [comment]
Gosh, Fedora 31 still has csync2 < version 2.0 ??!!!
the best is to remove csync2 package and compile it yourself from this git.
I had to do that anyhow on Fedora 30

**Comment by mvrk69** [comment]
Thanks, that fixed the problem, now with csync2 2.0 works fine.

**Comment by ROBERT-MCDOWELL** [comment]
you're welcome!

**Comment by lge** [comment]
well then ;-) ---> closed.
